x-global-environment: &global
  env_file:
    - envs/.env # env file - NOT committed to Git

services:
  caddy:
    <<: *global # this will inherit all the envs from x-global-environment
    depends_on:
      - django
    image: caddy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - dgc-app-backend-caddy-data:/data/
      - dgc-app-backend-caddy-data:/config/
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./staticdocs:/srv/staticdocs

  # Django Ninja API and test OIDC provider
  django: &django
    <<: *global # this will inherit all the envs from x-global-environment
    build:
      dockerfile: django.Dockerfile 
    image: dgc-app-backend-django:built # build image and save for use by other containers
    depends_on:
      - postgres
    volumes:
      - .:/app/
    environment:
      - RUN_TEST_OIDC_PROVIDER=true
    command: s/django/start-dev
    restart: always

  # Example SPA consumer of the API
  demo:
    <<: *global # this will inherit all the envs from x-global-environment
    build:
      dockerfile: demo.Dockerfile
    image: dgc-app-backend-demo:built # build image and save for use by other containers
    depends_on:
      - django
    volumes:
      - .:/app/
    # Workdir is set to /app/demo in the Dockerfile
    command: ../s/demo/start-dev
    # command: sleep 100000
    restart: always

  postgres:
    <<: *global # this will inherit all the envs from x-global-environment
    image: postgres:17.6
    volumes:
      - dgc-app-backend-postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  dgc-app-backend-caddy-data:
  dgc-app-backend-postgres-data: