# Generated by Django 5.2.8 on 2025-12-16 14:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_name', models.CharField(max_length=300)),
                ('encrypted_date_of_birth', models.CharField(max_length=300)),
                ('sex', models.PositiveSmallIntegerField(choices=[(0, 'male'), (1, 'female')])),
                ('gestation_days', models.PositiveIntegerField(blank=True, null=True)),
                ('reference', models.CharField(choices=[('uk-who', 'uk-who'), ('turner', 'turner'), ('trisomy-21', 'trisomy-21'), ('trisomy-21-aap', 'trisomy-21-aap'), ('cdc', 'cdc'), ('who', 'who')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_reference', models.CharField(choices=[('uk-who', 'uk-who'), ('turner', 'turner'), ('trisomy-21', 'trisomy-21'), ('trisomy-21-aap', 'trisomy-21-aap'), ('cdc', 'cdc'), ('who', 'who')], max_length=20)),
                ('encrypted_name', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observation_type', models.PositiveSmallIntegerField(choices=[(1, 'height'), (2, 'weight'), (3, 'ofc')])),
                ('encrypted_observation_date', models.CharField(max_length=300)),
                ('days_since_birth', models.PositiveIntegerField()),
                ('observation_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.child')),
            ],
        ),
        migrations.CreateModel(
            name='DGCResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(choices=[('uk-who', 'uk-who'), ('turner', 'turner'), ('trisomy-21', 'trisomy-21'), ('trisomy-21-aap', 'trisomy-21-aap'), ('cdc', 'cdc'), ('who', 'who')], max_length=20)),
                ('encrypted_dgc_api_result', models.CharField(max_length=10000)),
                ('corrected_sds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('corrected_centile', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('chronological_sds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chronological_centile', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.observation')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salt', models.CharField(max_length=150)),
                ('iterations', models.IntegerField(default=100000)),
                ('encrypted_organisation_key', models.CharField(max_length=300)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='ChildOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_child_key', models.CharField(max_length=300)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.child')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.organisation')),
            ],
            options={
                'unique_together': {('child', 'organisation')},
            },
        ),
        migrations.CreateModel(
            name='UserOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_creator', models.BooleanField()),
                ('encrypted_organisation_key', models.CharField(max_length=300)),
                ('encrypted_user_name', models.CharField(max_length=300)),
                ('encrypted_user_email', models.CharField(max_length=300)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
            options={
                'unique_together': {('user', 'organisation')},
            },
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('oauth_iss', models.CharField(max_length=300)),
                ('hashed_sub', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('salt', models.CharField(max_length=150)),
                ('iterations', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
            options={
                'unique_together': {('oauth_iss', 'hashed_sub')},
            },
        ),
    ]
