# Generated by Django 5.2.6 on 2025-09-11 20:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('birth_date', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('salt', models.CharField(max_length=150)),
                ('iterations', models.IntegerField(default=100000)),
            ],
        ),
        migrations.CreateModel(
            name='UserPatientKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=300)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userregistration')),
            ],
            options={
                'unique_together': {('user', 'patient')},
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='users',
            field=models.ManyToManyField(related_name='patients', through='backend.UserPatientKey', to='backend.userregistration'),
        ),
    ]
