# Generated by Django 5.2.8 on 2025-12-03 13:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='iterations',
        ),
        migrations.RemoveField(
            model_name='user',
            name='salt',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('oauth_iss', models.CharField(max_length=300)),
                ('hashed_sub', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('salt', models.CharField(max_length=150)),
                ('iterations', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
            options={
                'unique_together': {('oauth_iss', 'hashed_sub')},
            },
        ),
    ]
