name: Deploy to staging

on:
  workflow_dispatch:
  push:
    branches:
      - live

jobs:
  pr-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full code repo
        uses: actions/checkout@v4

      - name: Run deploy script
        run: s/deploy
